### ISSUE TITLE
name field is missing in some files

### ISSUE THREAD

**Issue by himansh-gjr** [navgurukul/newton#135]
ngMeta : name field is missing in some files maybe that's a reason name/headings are not showing the some courses like recursion, Lisit 101, English 401, Hangman, English 101
![Issues recursion](https://user-images.githubusercontent.com/77732259/114521456-0e8f5500-9c60-11eb-8aa4-4be2d0a3b761.png)

**Comment by abhishekgupta92** [comment]
Link of the page?

Abhishek Gupta ***@***.***>
CEO & Co-founder
Read about us at Forbes India 30u30
<https://www.forbesindia.com/article/30-under-30-2020/navgurukul-cracking-the-code-to-success/57717/1>
, TOI
<https://timesofindia.indiatimes.com/home/sunday-times/these-school-dropouts-have-cracked-the-code-to-a-better-life/articleshow/71458732.cms>
or
follow our blog <http://medium.com/navgurukul> for regular updates. You can
contribute using navgurukul.org/donate. Each rupee matters.

**Comment by Surabhi-yadav** [comment]
Yar dosto, kuch tarika hai kya isko pura unsubscribe karne ka? Alag alag
threads ko unsubscribe karna padhta hai.

Tumhi log hata do. Thanks!

**Comment by himansh-gjr** [comment]
these are some pages where I found this issue  :- 

https://merakilearn.org/course/53/exercise/1939
https://merakilearn.org/course/80/exercise/1993
https://merakilearn.org/course/58/exercise/1697
https://merakilearn.org/course/79/exercise/1957
