### ISSUE TITLE
lot's of courses lot's of confusion

### ISSUE THREAD

**Issue by shivam8800** [navgurukul/newton#45]
Recently,  I get to know about the confusion of courses, I think there should be a pattern to completing  saral courses like at saral home page there should be counter or number for each course or we can restrict the user to jump over another course before completing others one something like that
I will give a clear path to every student for their learning and It will reduce the old students or volunteer efforts to tell every new student, what they need to do or from where they have to start their learning.
Did you guy's get my point here ?

**Comment by abhishekgupta92** [comment]
Yeah! We are working on it. Thoda slow chal raha hai kaam, but this is definitely on the charts :)
